### ISSUE TITLE
Error with trying to load my own server

### ISSUE THREAD

**Issue by enbear** [CyclopsMC/CyclopsCore#171]
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem:

1. download the latest version of forge server
2. download latest version of cyclops core and put it in the mods folder of the forge server
3. run the forge server

#### Expected behaviour:

i expect when you run the server it wont allow you due to a locked registry.

#### Versions:

- This mod: cyclops core 1.19-1.17.0
- Minecraft: 1.19.1
- Forge: 42.0.0

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by a-sakharov** [comment]
Same thing happens for me, log: https://pastebin.com/y0aZEpdr

<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/y0aZEpdr">2022-08-04 19:08:12,363 main WARN Advanced terminal features are not available i - Pastebin.com</a></strong></div><div>Pastebin.com is the number one paste tool since 2002. Pastebin is a website where you can store text online for a set period of time.</div></blockquote>

**Comment by rubensworks** [comment]
Fixed in new releases.
