### ISSUE TITLE
[1.20]Server Crash due to Long Tick Time

### ISSUE THREAD

**Issue by windy664** [CyclopsMC/CyclopsCore#176]
#### Issue type:

- :bug: Bug 

____

#### Short description:
The server crashes due to a single server tick taking 60 seconds, which is significantly longer than the expected maximum tick time of 0.05 seconds. This results in a ServerHangWatchdog error.

#### Steps to reproduce the problem:

1.Start the Minecraft server with the relevant mods installed 
2.Wait for a while or perform certain actions 

#### Expected behaviour:
the server should be able to handle ticks within the maximum allowed time of 0.05 seconds, and should not crash due to a ServerHangWatchdog error.

____

#### Versions:

- This mod: 1.18.6
- Minecraft: 1.20.1
- Forge: 47.1.3

#### Log file:
[crash-2023-07-16_19.40.53-server.txt](https://github.com/CyclopsMC/CyclopsCore/files/12063922/crash-2023-07-16_19.40.53-server.txt)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
The stacktrace is just showing a chunk being loaded. Nothing special that ID is doing there.
Your machine may just be overloaded due to insufficient RAM.
Also, I see there's a mixin on the `Level` class, which might indicate another mod messing with chunkloading, and causing this issue.
I recommend removing mods to see which mod is causing the issue.

**Comment by windy664** [comment]
> Reference in new i

移除哪个mod？？？
