### ISSUE TITLE
Item render crash in smp

### ISSUE THREAD

**Issue by MrTubzy456** [CyclopsMC/CyclopsCore#18]
http://pastebin.com/m65HLHBn

I can't give you much more info. One of my players gave this to me. We're on version 1.9.4-0.6.3.

**Comment by rubensworks** [comment]
If that player could give some additional info, that'd be great.
This one will otherwise be a very difficult one to debug.

**Comment by FlawlessGecko** [comment]
I am the user having the error here is a later log http://pastebin.com/3JUy0ZjY it seems to be some block or item in my inventory. I killed myself and was able to open my inventory with no items in it but I opened my grave and items went back into inventory since then I click on anything that open my inventory it crash's such as crafting table,e,chest,refined storage. If you need more info I am glad to help.

**Comment by rubensworks** [comment]
@FlawlessGecko Which items were in your inventory when you crashed?
I am looking for items from one of the following mods: EvilCraft, Integrated Dynamics, Fluid Converters, Colossal Chests, Structured Crafting.

**Comment by FlawlessGecko** [comment]
@rubensworks Lots of items I can't look at them due to crash if I press my inventory button.I had recently mined and was building. My hot-bar contains wand swapper and some clay blocks. I just tried to drop the items on the ground and crashed out with this  http://pastebin.com/va3Br3Ev.

**Comment by rubensworks** [comment]
@FlawlessGecko Ah, in this crash I can see what is causing is. Apparently you picked up a Blood Stained Block from EvilCraft somehow. I'll create an issue in the EC repo.

**Comment by FlawlessGecko** [comment]
@rubensworks Thanks thought that might do the trick.

**Comment by rubensworks** [comment]
Fixed in CyclopsMC/EvilCraft#412
