### ISSUE TITLE
[Bug]Rendering crash when used in conjunction with embeddium or sodium on 1.21.

### ISSUE THREAD

**Issue by Kevin-Marsh** [CyclopsMC/CyclopsCore#187]
Installing Cyclops and Integrated Dynamics alongside Embeddium or Sodium on 1.21 causes a particle rendering crash.

https://mclo.gs/01itE0d

**Comment by rubensworks** [comment]
Please report this to their issue tracker, given that they significantly change the internals of vanilla.

**Comment by IMS212** [comment]
I've looked into it, and the bug does indeed seem to be on CC's side. It passes entirely null data when using a buffer builder wrapper, instead of the original builder's data. https://github.com/CyclopsMC/CyclopsCore/blob/c9635c72d52da9145175946a460a12972a79a935/src/main/java/org/cyclops/cyclopscore/client/particle/ParticleBlur.java#L151

**Comment by rubensworks** [comment]
Thanks for looking into this @IMS212! The wrapper was indeed a hack that seemed to work fine in vanilla, but now appears to show its limitations.
I'll look into your PR soon!
