### ISSUE TITLE
Update Minecraft and Forge

### ISSUE THREAD

**Issue by josephcsible** [CyclopsMC/CyclopsCore#72]
I noticed that this (and the rest of your mods) are all still building against Minecraft 1.12 and an old version of Forge. Can we bump this up to 1.12.1 and the newest version of Forge, since everything works there anyway? (If so, I can make the PR's if you want.)

**Comment by rubensworks** [comment]
I waited because Forge didn't have a recommended 1.12.1 release yet (now it does though).
But I would wait for 1.12.2, as Mojang announced that they would release it this week, and Forge will probably follow pretty soon.

I always try to bump the Forge version on all cyclops mods at once for consistency during development. And as this requires a bit of work, I try not to do it too often.

So in a couple of weeks or so, we should be good to go :-)
