### ISSUE TITLE
Release version 0.10.18

### ISSUE THREAD

**Issue by josephcsible** [CyclopsMC/CyclopsCore#73]
Any recipes that try to use non-integral XP values (#71) will crash the game on startup with a NumberFormatException if that change isn't present. Can you release what's in git now as 0.10.18, so I can add it as a minimum version dependency and start using it?

EDIT: Or if the answer to the questions I asked in CyclopsMC/IntegratedDynamics#272 about making more classes here is "yes", would you rather me do that first, to only need one release instead of two?

**Comment by rubensworks** [comment]
I will try to release new CC, ID and EC tomorrow evening.
If you'd be able to create those new classes in CC, that'd be great, otherwise it will be for the next release.

In case you want to be able to use the latest CC version in your ID dev environment, you can do this with this: https://github.com/CyclopsMC/IntegratedDynamics/blob/master-1.12/gradle/forge.gradle#L11-L12

In any case, when I release a new ID version, I'll bump the minimal required CC version.

**Comment by josephcsible** [comment]
Sounds like a plan. I'll try to get those classes written tonight.

**Comment by josephcsible** [comment]
Yeah, there's no way those classes will be done. Just go ahead and release it with the one change.

**Comment by rubensworks** [comment]
@josephcsible Fyi, I won't make it this evening to make a new release. I'll try again tomorrow, Sunday or Monday. So feel free to PR those new classes in if you have time.

(Btw, are you reachable via IRC, Discord or something else? Might be easier to communicate than via GitHub issues)

**Comment by josephcsible** [comment]
> (Btw, are you reachable via IRC, Discord or something else? Might be easier to communicate than via GitHub issues)

How about Google Hangouts?

**Comment by rubensworks** [comment]
That's a bit inconvenient for me, since they support XMPP anymore :(
But email might be easier then, my gmail account is the same as on github here, feel free to send me a mail.
